### ISSUE TITLE
Duplicate nodes added several times 

### ISSUE THREAD

**Issue by JasonKAls** [mengesb/chef-compliance#21]
Hello Sous-chefs,

I'm trying to automate the process for provisioning a node with a fully installed and configured chef-compliance server in each of my environments.  I've noticed that the Cookbook is capable of making sure it doesn't add duplicate keys (same name and/or Key ID), however it does not recognize nodes that have the same name and/or IP address.  This causes multiple duplicates of the same to be added.  I'm writing code to try and address this issue on my end, but wondering if you can look into this as well.

Thanks in advance,
Jason Als

**Comment by mengesb** [comment]
Not sure what you mean by same name/IP in the cookbook. It's pretty straight forward. Could you elaborate

**Comment by JasonKAls** [comment]
Closing issue.  @mengesb helped me determine this is an issue with my execution rather than the actual Cookbook.
