### ISSUE TITLE
chef-ingredient version is not compatiable?

### ISSUE THREAD

**Issue by pariminaresh** [mengesb/chef-compliance#22]
**Steps followed:**
 - Created a wrapper for chef-compliance and running
 - Failing with the below issue. Possibly because of the dependant chef-ingredient version 2.1.3. Tested the same with chef-ingredient version as 1.0.0. Worked.

**Issue:**

 NoMethodError
--------------------
           undefined method `fqdn_resolves?' for ChefIngredientCookbook::Helpers:Module

**Possible solutions**
Possible Solution could be:
  1. adding support for the library method `fqdn_resolves?` in the latest chef-ingredient version 2.1.3.
  2. (Or) removing dependency of `fqdn_resolves`.

**Comment by josephholsten** [comment]
was removed from chef ingregent cookbook at https://github.com/chef-cookbooks/chef-ingredient/commit/34876d55e2d1770e8a5789e5290bb4b78a608a40#diff-38a4aeddb4e620724d3b85362cb8b939

**Comment by josephholsten** [comment]
I'm okay with removing the fqdn check. Honestly, the ideal solution would be to have a meaningful configtest error bubble up from compliance itself.

**Comment by mengesb** [comment]
So it would appear that a number of cookbooks utilizing the chef-ingredient method to install chef properties relied on `fqdn_resolves?` and other `fqdn_` helpers. Seems that's back in version 2.1.10 of the chef-ingredient cookbook. I'm attempting to update versions and such, however tests against latest chef-13 client and this cookbook are netting chef-ingredient attempting to use the chef-backend resource.... not sure why.... still debugging that one but in the mean time I'm checking with chef client 12.21.26 (latest chef-client 12.x)

**Comment by mengesb** [comment]
I'm waiting on some feedback on [chef-cookbooks/chef-ingredient/issues/206](https://github.com/chef-cookbooks/chef-ingredient/issues/206) for now...  The behavior around compliance and the newest chef-ingredient isn't very predictable ...

**Comment by mengesb** [comment]
ingredient no longer supports compliance since it is now a feature integrated into Chef Automate.
