### ISSUE TITLE
deploying on AWS instance results in using private dns name instead of the public

### ISSUE THREAD

**Issue by lmilbaum** [mengesb/chef-compliance#23]
The attribute ['chef-compliance ']['api_fqdn'] is set to 'chef-compliance.depy.io'.
But, after running the setup the redirected endpoint is populated with the private dns name of the AWS instance.

**Comment by josephholsten** [comment]
Looks like this is being set by https://github.com/sous-chefs/chef-compliance/blob/master/attributes/default.rb#L31
```
default['chef-compliance']['api_fqdn'] = node['fqdn']
```

How are you setting `node['chef-compliance']['api_fqdn']`?

**Comment by lmilbaum** [comment]
I am. 
Figured out how to resolve this issue.  Replaced the line in the template file:
compliance_fqdn "<%= node['chef-compliance']['api_fqdn'] %>"
with
fqdn "<%= node['chef-compliance']['api_fqdn'] %>"

**Comment by mengesb** [comment]
I suppose the changed the compliance configuration file to use `fqdn` instead of `compliance_fqdn`? this wasn't so in prior versions
