### ISSUE TITLE
cant login to default install

### ISSUE THREAD

**Issue by willejs** [mengesb/chef-compliance#8]
I get a 404 page not found. The logs dont show anything, i guess this is because its not being configured correctly? Im going to figure it out and make a PR i guess.

**Comment by willejs** [comment]
This is because chef compliance is expecting the FQDN in the config, so https://default-opscode-ubuntu-1404:4443/#/setup works if you port forward to local host in test kitchen and set it in the hosts file.

**Comment by mengesb** [comment]
FQDN is indeed a requirement. Looking forward to the PR!

**Comment by willejs** [comment]
I fixed this by setting the private_network IP of the instance in kitchen, then setting that ip in my hosts file.
It might be worth putting this in the docs, as i cant think of a simple way to do this.
I am going to do quite a lot of work on compliance, so it would be good to pool efforts somehow?
What are your plans?

**Comment by mengesb** [comment]
There's a kitchen way of doing this. I'll look into it tonight and
hopefully have something tomorrow. I'll also look into docker if that's OK

**Comment by mengesb** [comment]
This is now resolved. The original problem was the base work was with chef-analytics cookbook, where the kitchen properties were specifying `chef-analaytics` instead of `chef-compliance`. I've fixed this, and also added the `vm_hostname` attribute as specified by kitchen docs.
